spring:
  application:
      name: gateway1
# TODO this should be set externally, e.g. in a docker-compose file      
  cloud:
    gateway:    
      server:
        webmvc:
          routes:
          - id: hello-route
            predicates:
              - Path=/hello/**
            uri: ${HELLO_SERVICE_URL:http://localhost:1010}
          - id: vaadin-ui-route
            predicates:
              - Path=/vaadin-ui/**
            uri: ${VAADIN_UI_URL:http://localhost:2600}            
          - id: vaadin-sso-route
            predicates:
              - Path=/vaadin-sso1/**
            uri: ${VAADIN_SSO_URL:http://localhost:2601}
            filters:
              - TokenRelay=
          - id: jenkins-route
            predicates:
              - Path=/jenkins/**
            uri: ${JENKINS_URL:http://10.10.3.27:7778}
          - id: api-los-ap-svc-route
            predicates:
              - Path=/api/legacy/los-ap-svc/**
            uri: ${API_URL:http://localhost:2501}            
            filters:
              - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: cashier-dev2-client
            authorization-grant-type: authorization_code
            scope: openid,profile,email,roles
        provider:
          keycloak:
            issuer-uri: https://ppusso.devoutsys.com/realms/los-realm
            token-uri: https://ppusso.devoutsys.com/oauth2/token
            user-name-attribute: preferred_username
